add completed task on arrays
alexeymelekhov-dev/study pull request #1
Opened 2021-11-10 16:33 UTC by alexeymelekhov-dev

2021-11-12 12:16 UTC, moklidia requested changes

2021-11-12 12:16 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +          array.each do |el|
Попробуй реализовать без вложенных циклов. Можно разделить это на две операции: поиск максимального числа и обработку массива с заменой.

2021-11-12 12:16 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +          _array.find_index(_query)
_ ставится только перед неиспользуемыми переменными, а ты их здесь используешь

2021-11-13 10:28 UTC, Yoffic requested changes

2021-11-13 10:28 UTC, Yoffic commented on test/exercise/arrays/solution.rb
> +          end
Давай здесь воспользуемся тернарным оператором `condition ? result_for_true : result_for_false`

2021-11-13 10:28 UTC, Yoffic commented on test/exercise/arrays/solution.rb
> +          array.find_index(query)
В рамках задания нельзя использовать стандартные функции для поиска элемента в массиве. Давай перепишем рекурсивную функцию, чтобы она не только проверяла наличие элемента, но и возвращала индекс этого элемента

2021-11-15 07:28 UTC, moklidia approved these changes

2021-11-17 14:52 UTC, merged